spring:
  application:
    name: movie-booking
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/movie-booking
    username: movie-booking
    password: movie-booking

  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200

logbook:
  predicate:
    exclude:
      - path: /actuator/**
  format:
    style: json

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: trace